### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dong20dong** [seolhokim/BipedalWalker-BranchingDQN#1]
I am a little confused about why you have added a "self.value" layer after "self.actions" layer for QNetwork.

>  self.actions = nn.ModuleList(self.actions)
    self.value = nn.Sequential(nn.Linear(state_space*10,state_space*5),
          nn.ReLU(),
          nn.Linear(state_space*5,1)
          )

Meanwhile, I don't understand why value is added to every action.

> for i in range(len(actions)):
    actions[i] = actions[i] - actions[i].max(-1)[0].reshape(-1,1)
    actions[i] += value

Could you please explain your thoughts? Thank you very much!

**Comment by seolhokim** [comment]
hi, you can figure it out in branchingdqn paper expression(2)

thanks for your attention.
seolho kim.

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-04-25 (목) 23:48:40 (GMT+09:00)
Subject: [seolhokim/BipedalWalker-BranchingDQN] question (Issue #1)

I am a little confused about why you have added a "self.value" layer after "self.actions" layer for QNetwork.
`
self.actions = nn.ModuleList(self.actions)
self.value = nn.Sequential(nn.Linear(state_space10,state_space5),
nn.ReLU(),
nn.Linear(state_space*5,1)
)
Meanwhile, I don't understand why value is added to every action.
for i in range(len(actions)):
actions[i] = actions[i] - actions[i].max(-1)[0].reshape(-1,1)
actions[i] += value
`
Could you please explain your thoughts? Thank you very much!

**Comment by dong20dong** [comment]
I see. Thanks!
